name: tuiicore
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  animated_check: ^1.0.5
  audio_session: ^0.1.16
  bloc: ^8.1.2
  cloud_firestore: ^4.4.3
  dartz: ^0.10.1
  defer_pointer: ^0.0.2
  equatable: ^2.0.5
  
  firebase_auth: ^4.10.1
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.0.9
  form_validation: 2.1.0+21
  i18n_extension: ^7.0.0
  intl: ^0.18.1
  just_audio: ^0.9.35
  just_audio_platform_interface: ^4.2.1
  just_audio_web: ^0.4.8
  localstore: ^1.3.4
  material_design_icons_flutter: ^6.0.7096
  pdf_render: ^1.3.4
  regexed_validator: ^2.0.0+1
  rxdart: ^0.27.7
  stream_chat_flutter: ^5.3.0
  uuid: ^3.0.6
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  export_generator: ^0.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
